#!/usr/bin/env fish

echo "Building"
clj -T:build uber

set artifact (ls target | grep "synchro.*\.jar")

echo "Uploading $artifact to server"
scp "target/$artifact" synchro:~

ssh synchro "bash -s" < scripts/exec-deploy.sh

if test $status -eq 0
  echo "Cleaning up old jars"
  ./scripts/cleanup
end
